### ISSUE TITLE
Need helpb to fix it

### ISSUE THREAD

**Issue by DavidJBrockway** [NetherManiacsKingdom/MCG76-HG-v2#1]
Plz can you help me fix it

**Comment by erkam2002** [comment]
Why add you always copyied plugins?

**Comment by DavidJBrockway** [comment]
well i ahd the old code it a great hg plugin needs fixing

**Comment by matthew4444** [comment]
WE NEED TO GET THESE PLUGINS DONE!

**Comment by DavidJBrockway** [comment]
ik

**Comment by DavidJBrockway** [comment]
ib add chest and traning and map this hg works need update plz look at erro

**Comment by matthew4444** [comment]
Can we make a lucky block plungin

**Comment by erkam2002** [comment]
Yes

**Comment by matthew4444** [comment]
Can we do it now plz

**Comment by erkam2002** [comment]
Yes wait

**Comment by matthew4444** [comment]
Hello

**Comment by matthew4444** [comment]
K

**Comment by matthew4444** [comment]
How long

**Comment by erkam2002** [comment]
Idk

**Comment by matthew4444** [comment]
Hello

**Comment by matthew4444** [comment]
K

**Comment by NetherOwner** [comment]
Hi

**Comment by matthew4444** [comment]
Il start the plugin and il tell u when i need help with the plugin

**Comment by erkam2002** [comment]
How can i create a Src order?

**Comment by NetherOwner** [comment]
Guys are we done wirh EnderAuth?

**Comment by matthew4444** [comment]
not yet

**Comment by matthew4444** [comment]
I can make src folder give me a sec

**Comment by NetherOwner** [comment]
I know but no one is working at it can we not work on it plss

**Comment by HittmanA** [comment]
GUYS STOP WORKING ON NEW PLUGINS BEFORE OLD ONES ARE FINISHED
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by erkam2002** [comment]
How create i src order?

**Comment by NetherOwner** [comment]
YEHA!

**Comment by HittmanA** [comment]
WE HAVE SO MANY UNFINISHED PLUGINS

**Comment by NetherOwner** [comment]
So why are we not done with enderauth we need to be done with that

**Comment by HittmanA** [comment]
DO NOT START ANY MORE PLUGINS TILL WE FINISH THE OLD ONES

**Comment by NetherOwner** [comment]
Yes

**Comment by HittmanA** [comment]
IKR NetherOwner

**Comment by NetherOwner** [comment]
Yeah evertime i go to github there is a new plugin

**Comment by HittmanA** [comment]
If we don't finish old plugins no one is gonna follow us because we will never finish them

**Comment by NetherOwner** [comment]
Yeah

**Comment by HittmanA** [comment]
Until we finish enderauth any new plugin repos will be deleted

**Comment by HittmanA** [comment]
From now on

**Comment by DavidJBrockway** [comment]
i fixed npc

**Comment by NetherOwner** [comment]
Yeah

**Comment by DavidJBrockway** [comment]
and playerlisener

**Comment by HittmanA** [comment]
@matthew4444 Are you watching and listening?

**Comment by DavidJBrockway** [comment]
i dont get the other erro

**Comment by NetherOwner** [comment]
David work on enderauth

**Comment by DavidJBrockway** [comment]
what it need

**Comment by HittmanA** [comment]
David plz work on ender auth

**Comment by erkam2002** [comment]
Is enderauth not finished?

**Comment by DavidJBrockway** [comment]
i am working on magiccarpet

**Comment by HittmanA** [comment]
NO BECAUSE MATTHEW KEEPS MAKING NEW REPOS!

**Comment by DavidJBrockway** [comment]
ok link

**Comment by NetherOwner** [comment]
Its need email system and more you can look it on the description in the plugin

**Comment by DavidJBrockway** [comment]
ik

**Comment by HittmanA** [comment]
give him the link

**Comment by erkam2002** [comment]
Hmmm how go that that is difficult

**Comment by NetherOwner** [comment]
To what

**Comment by DavidJBrockway** [comment]
it can work only if mysql

**Comment by HittmanA** [comment]
Ender Auth nether owner

**Comment by NetherOwner** [comment]
Kk

**Comment by DavidJBrockway** [comment]
i am working on pocketauth

**Comment by DavidJBrockway** [comment]
it still beta it has email in sql

**Comment by HittmanA** [comment]
Finish EnderAuth before any other plugins OK!

**Comment by DavidJBrockway** [comment]
i try

**Comment by NetherOwner** [comment]
https://github.com/NetherManiacsKingdom/EnderAuth

**Comment by DavidJBrockway** [comment]
i fixed some hg bugs

**Comment by DavidJBrockway** [comment]
and been working on ender world genrator

**Comment by HittmanA** [comment]
Honestly we have so many repos I can't keep up!

**Comment by DavidJBrockway** [comment]
ik

**Comment by NetherOwner** [comment]
Work on https://github.com/NetherManiacsKingdom/EnderAuth rigth NOW!

**Comment by DavidJBrockway** [comment]
i try

**Comment by NetherOwner** [comment]
K

**Comment by HittmanA** [comment]
Everyone needs to focus on EnderAuth. Until its done plz don't work on any other plugins!

**Comment by NetherOwner** [comment]
Æ

**Comment by DavidJBrockway** [comment]
keep tjis open

**Comment by HittmanA** [comment]
Why'd you do that nether?

**Comment by DavidJBrockway** [comment]
what

**Comment by matthew4444** [comment]
We need to work on luckyblocks now, i need help with the pligin,plz help,were a pocketmine plugin development tezm!

**Comment by matthew4444** [comment]
Plugin

**Comment by HittmanA** [comment]
NO MATTHEW FINISH THE OLD PLUGINS THEN DO THAT

**Comment by DavidJBrockway** [comment]
i been add code to magicacapet

<?php

namespace NetherManiacsKingdom\MagicCarpet;

use pocketmine\command\Command;
use pocketmine\command\CommandSender;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\TextFormat;
use pocketmine\Player;
use pocketmine\Server;
use pocketmine\utils\Config;
use pocketmine\level\Position;
use pocketmine\level\Level;
use pocketmine\block\Block;
use pocketmine\math\Vector3 as Vector3;
use pocketmine\event\Listener;
use pocketmine\event\player\PlayerMoveEvent;

**Comment by HittmanA** [comment]
WE HAVE SOOOO MANY UNFINISHED PLUGINS SO FINISH THEM BEFORE MAMING NEW ONES!

**Comment by DavidJBrockway** [comment]
i have magica carpet done

**Comment by DavidJBrockway** [comment]
we need a clean up what wrong with ender auth

**Comment by HittmanA** [comment]
Take a look at the repo

**Comment by HittmanA** [comment]
https://github.com/NetherManiacsKingdom/EnderAuth is the url

**Comment by DavidJBrockway** [comment]
i have there northing wrong

**Comment by DavidJBrockway** [comment]
enails

**Comment by HittmanA** [comment]
Take a look at the unchecked boxes in the TODO

**Comment by matthew4444** [comment]
@DavidJBrockway  can u work on lucky blocks

**Comment by HittmanA** [comment]
NO

**Comment by HittmanA** [comment]
ONLY WORK ON ENDERAUTH TILL IT IS DONE!

**Comment by HittmanA** [comment]
PLZ we need to finish it!

**Comment by DavidJBrockway** [comment]
ok i try i am new but it may carsh

**Comment by HittmanA** [comment]
what are you working on?

**Comment by DavidJBrockway** [comment]
ender now

**Comment by HittmanA** [comment]
ok good.

**Comment by DavidJBrockway** [comment]
ok email hard

**Comment by HittmanA** [comment]
@matthew4444 ?
Can i help with lucky blocks?

**Comment by HittmanA** [comment]
Use bitter from now on plz btw

**Comment by DavidJBrockway** [comment]
i canr add email i would need to re code it all

**Comment by HittmanA** [comment]
I am going to bitter matthew

**Comment by HittmanA** [comment]
Why david?

**Comment by DavidJBrockway** [comment]
if i add email the holed code would break i would need to add task folder ect

**Comment by HittmanA** [comment]
I invited you to bitter room. Join and we will talk there

**Comment by DavidJBrockway** [comment]
looking at leet auth code my be it coud work

**Comment by DavidJBrockway** [comment]
<?php

/*********************************************************
 * Copyright by LEET.                                    *
 * Free to use. No modifications allowed.                *
 * Please contact info@leet.cc if you have any questions.*
 ********************************************************/

namespace Leet\LeetAuth\command;

use Leet\LeetAuth\LeetAuth;
use Leet\LeetAuth\task\RegisterTask;
use Leet\LeetAuth\task\UpdateTask;
use pocketmine\command\Command;
use pocketmine\command\CommandExecutor;
use pocketmine\command\CommandSender;
use pocketmine\Player;
use pocketmine\utils\TextFormat;

class RegisterCommand implements CommandExecutor {

    private $plugin;

    public function __construct(LeetAuth $plugin) {
        $this->plugin = $plugin;
    }

    public function onCommand(CommandSender $sender, Command $command, $label, array $args) {

        if(!$sender instanceof Player) {
            $sender->sendMessage(TextFormat::RED.'Only players can register accounts.');
            return true;
        }

        /** @var Player $player */
        $player = $sender;

        if(count($args) < 2 and (count($args) < 1 or !isset($this->plugin->needsUpdate[$player->getUniqueId()->toString()]))) return false;

        if(strlen($player->getName()) > 16) {
            $player->sendMessage($this->plugin->getMessageHandler()->loginFailNameLength);
            return true;
        }

        $email = $args[0];

        # Check if the email is too long.
        if(strlen($email) > 64) {
            $player->sendMessage($this->plugin->getMessageHandler()->loginFailEmailLength);
            return true;
        }

        # Check if the email is valid according to PHP email filter.
        if(!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $player->sendMessage($this->plugin->getMessageHandler()->loginFailEmailNotValid);
            return true;
        }

        # If the player is in the needsUpdate array that means he/she needs to update the associated email.
        if(isset($this->plugin->needsUpdate[$player->getUniqueId()->toString()])) {
            $this->plugin->getServer()->getScheduler()->scheduleAsyncTask(new UpdateTask($this->plugin->getDescription()->getVersion(), $email, $player->getName(), $player->getUniqueId()->toString(),
                $player->getAddress(), $this->plugin->getServer()->getIp(), $this->plugin->getServer()->getPort(), $this->plugin->token));
            return true;
        }

        $password = $args[1];

        if(strlen($password) < $this->plugin->getPasswordLength()) {
            $player->sendMessage($this->plugin->getMessageHandler()->loginFailPassLength);
            return true;
        }

        # Prepare password to be sent.
        $password = $this->plugin->hash(strtolower($player->getName()), $password);


        # Schedule a register task.
        $this->plugin->getServer()->getScheduler()->scheduleAsyncTask(new RegisterTask($this->plugin->getDescription()->getVersion(),
            $player->getName(), $email, $password, $player->getUniqueId()->toString(), $player->getAddress(),
            $this->plugin->getServer()->getIp(), $this->plugin->getServer()->getPort(), $this->plugin->token));

        return true;

    }

}

**Comment by DavidJBrockway** [comment]
ok

**Comment by DavidJBrockway** [comment]
i work on fixing other plugins

**Comment by HittmanA** [comment]
No join the gitter room

**Comment by DavidJBrockway** [comment]
link

**Comment by HittmanA** [comment]
https://gitter.im/matthew4444/NetherManiacsKingdom

**Comment by HittmanA** [comment]
see you there

**Comment by DavidJBrockway** [comment]
k
